import "./globals.css";

import type { Metadata } from "next";

import { Footer } from "@/components/layout/Footer";
import { FullScreenContainer } from "@/components/layout/FullScreenContainer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <Header />
        <FullScreenContainer>{children}</FullScreenContainer>
        <Footer />
      </body>
    </html>
  );
}
